from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

test_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'MountingHole_Pad', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'Mounting Hole with connection', 'match_pin_substring':False, 'F2':'', 'keywords':'mounting hole', 'F1':'MountingHole_Pad', 'F3':'', 'F0':'H', 'datasheet':'~', 'ref_prefix':'H', 'num_units':1, 'fplist':['MountingHole*Pad*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'MountingHole:MountingHole_2.5mm_Pad', 'pins':[
            Pin(num='1',name='1',func=Pin.types.INPUT,do_erc=True)] }),
        Part(**{ 'name':'Raspberry_Pi_2_3_Default', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'', 'match_pin_substring':False, 'F2':'', 'keywords':'', 'F1':'Raspberry_Pi_2_3_Default', 'F3':'', 'F0':'J', 'datasheet':'', 'ref_prefix':'J', 'num_units':1, 'fplist':['PinHeader*2x20*P2.54mm*Vertical*', 'PinSocket*2x20*P2.54mm*Vertical*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'FIN HAT Template:PinSocket_2x20_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='3V3',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='10',name='GPIO15/RXD',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='11',name='GPIO17',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='12',name='GPIO18/PWM0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='13',name='GPIO27',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='14',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='15',name='GPIO22',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='16',name='GPIO23',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='17',name='3V3',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='18',name='GPIO24',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='19',name='MOSI0/GPIO10',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='2',name='5V',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='20',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='21',name='MISO0/GPIO9',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='22',name='GPIO25',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='23',name='SCLK0/GPIO11',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='24',name='~CE0~/GPIO8',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='25',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='26',name='~CE1~/GPIO7',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='27',name='ID_SD/GPIO0',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='28',name='ID_SC/GPIO1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='29',name='GCLK1/GPIO5',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='3',name='SDA/GPIO2',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='30',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='31',name='GCLK2/GPIO6',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='32',name='PWM0/GPIO12',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='33',name='PWM1/GPIO13',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='34',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='35',name='GPIO19/MISO1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='36',name='GPIO16',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='37',name='GPIO26',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='38',name='GPIO20/MOSI1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='39',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='4',name='5V',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='40',name='GPIO21/SCLK1',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='5',name='SCL/GPIO3',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='6',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='7',name='GCLK0/GPIO4',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='8',name='GPIO14/TXD',func=Pin.types.BIDIR,do_erc=True),
            Pin(num='9',name='GND',func=Pin.types.PWRIN,do_erc=True)] }),
        Part(**{ 'name':'POE_Header', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'', 'match_pin_substring':False, 'F2':'', 'keywords':'', 'F1':'POE_Header', 'F3':'', 'F0':'J', 'datasheet':'', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_2x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'FIN HAT Template:PinSocket_2x02_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='TR01',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='TR00',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='TR03',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='TR02',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Co-Processor_Header', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'', 'match_pin_substring':False, 'F2':'', 'keywords':'', 'F1':'Co-Processor_Header', 'F3':'', 'F0':'J', 'datasheet':'', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_2x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'FIN HAT Template:PinSocket_2x09_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='PD14',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='SPI_MISO',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='11',name='PB11',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='12',name='DBG_RX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='PF6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='DBG_TX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='15',name='PF7',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='16',name='I2C_SDA',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='17',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='18',name='I2C_SCL',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='3v3_ON',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='PA2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='SPI_CS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='PA3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='SPI_SCLK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='PA4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='SPI_MOSI',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='PA5',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'USB_Header', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'', 'match_pin_substring':False, 'F2':'', 'keywords':'', 'F1':'USB_Header', 'F3':'', 'F0':'J', 'datasheet':'', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'FIN HAT Template:PinSocket_1x04_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='5V',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='D-',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='D+',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='GND',func=Pin.types.PASSIVE,do_erc=True)] })])